import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        "on-background": "#181c20",
        "tertiary": "#b81d17",
        "secondary-container": "#86f898",
        "inverse-primary": "#adc7ff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001a41",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#89fa9b",
        "surface-dim": "#d7dae0",
        "on-secondary-fixed": "#002108",
        "on-tertiary-fixed-variant": "#930004",
        "on-surface-variant": "#414754",
        "primary": {
          DEFAULT: "#005bbf",
          foreground: "#ffffff",
          container: "#1a73e8",
          fixed: "#d8e2ff",
          "fixed-dim": "#adc7ff",
        },
        "surface-container-low": "#f1f4fa",
        "on-error": "#ffffff",
        "outline-variant": "#c1c6d6",
        "secondary-fixed-dim": "#6ddd81",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#dfe3e8",
        "secondary": {
          DEFAULT: "#006e2c",
          foreground: "#ffffff",
          container: "#86f898",
          fixed: "#89fa9b",
          "fixed-dim": "#6ddd81",
        },
        "surface": "#f7f9ff",
        "inverse-surface": "#2d3135",
        "surface-tint": "#005bc0",
        "on-secondary-container": "#00722f",
        "on-surface": "#181c20",
        "on-tertiary-container": "#ffffff",
        "on-secondary-fixed-variant": "#005320",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#004493",
        "primary-container": "#1a73e8",
        "error": "#ba1a1a",
        "outline": "#727785",
        "surface-bright": "#f7f9ff",
        "inverse-on-surface": "#eef1f7",
        "on-tertiary-fixed": "#410001",
        "surface-container": "#ebeef4",
        "primary-fixed": "#d8e2ff",
        "on-secondary": "#ffffff",
        "tertiary-container": "#dc392c",
        "surface-variant": "#dfe3e8",
        "tertiary-fixed": "#ffdad5",
        "surface-container-high": "#e5e8ee",
        "tertiary-fixed-dim": "#ffb4a9",
        "on-primary-container": "#ffffff",
        "primary-fixed-dim": "#adc7ff",
        // Custom health portal colors
        health: {
          primary: "hsl(var(--health-primary))",
          secondary: "hsl(var(--health-secondary))",
          emergency: "hsl(var(--health-emergency))",
          blue: "hsl(var(--health-blue))",
          purple: "hsl(var(--health-purple))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      backgroundImage: {
        'gradient-health': 'var(--gradient-health)',
        'gradient-primary': 'var(--gradient-primary)',
      },
      boxShadow: {
        'health': 'var(--shadow-health)',
        'card': 'var(--shadow-card)',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-up": {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "slide-up": "slide-up 0.5s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
